// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBlScNte1Cyatbpo3ySkTGhCMrtyA1uI',
    appId: '1:442847638412:web:98e944e8e11fb211889ca9',
    messagingSenderId: '442847638412',
    projectId: 'levantam-f144e',
    authDomain: 'levantam-f144e.firebaseapp.com',
    databaseURL: 'https://levantam-f144e-default-rtdb.firebaseio.com',
    storageBucket: 'levantam-f144e.appspot.com',
    measurementId: 'G-5H04NK2S5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpIPgY7ZAHGwroESYsjPn4-TsAJSe8GfM',
    appId: '1:442847638412:android:78de2d0fa2a27620889ca9',
    messagingSenderId: '442847638412',
    projectId: 'levantam-f144e',
    databaseURL: 'https://levantam-f144e-default-rtdb.firebaseio.com',
    storageBucket: 'levantam-f144e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_y0XlsiXECiixJzbfINbtLIScOBp1Nk',
    appId: '1:442847638412:ios:a91354bc4894f518889ca9',
    messagingSenderId: '442847638412',
    projectId: 'levantam-f144e',
    databaseURL: 'https://levantam-f144e-default-rtdb.firebaseio.com',
    storageBucket: 'levantam-f144e.appspot.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_y0XlsiXECiixJzbfINbtLIScOBp1Nk',
    appId: '1:442847638412:ios:a91354bc4894f518889ca9',
    messagingSenderId: '442847638412',
    projectId: 'levantam-f144e',
    databaseURL: 'https://levantam-f144e-default-rtdb.firebaseio.com',
    storageBucket: 'levantam-f144e.appspot.com',
    iosBundleId: 'com.example.app2',
  );
}
